// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDFG2WBCiuOcncJ0KTrKtyypWpPcjGz8',
    appId: '1:382236211402:web:b9469c26afe16a4d399c33',
    messagingSenderId: '382236211402',
    projectId: 'whatsapp12-3b9d8',
    authDomain: 'whatsapp12-3b9d8.firebaseapp.com',
    storageBucket: 'whatsapp12-3b9d8.firebasestorage.app',
    measurementId: 'G-V47PJKFM8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7jwxpCrUpbGZZmqn3-BWjbj5G4ml-wQ',
    appId: '1:382236211402:android:23fafe5be1f413b7399c33',
    messagingSenderId: '382236211402',
    projectId: 'whatsapp12-3b9d8',
    storageBucket: 'whatsapp12-3b9d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQcVEKa-0NAGVoIEfWfkKeuWu9S2pQj08',
    appId: '1:382236211402:ios:8984252c21244dd3399c33',
    messagingSenderId: '382236211402',
    projectId: 'whatsapp12-3b9d8',
    storageBucket: 'whatsapp12-3b9d8.firebasestorage.app',
    iosBundleId: 'com.example.zytronicTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQcVEKa-0NAGVoIEfWfkKeuWu9S2pQj08',
    appId: '1:382236211402:ios:8984252c21244dd3399c33',
    messagingSenderId: '382236211402',
    projectId: 'whatsapp12-3b9d8',
    storageBucket: 'whatsapp12-3b9d8.firebasestorage.app',
    iosBundleId: 'com.example.zytronicTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSDFG2WBCiuOcncJ0KTrKtyypWpPcjGz8',
    appId: '1:382236211402:web:0b8da29604990224399c33',
    messagingSenderId: '382236211402',
    projectId: 'whatsapp12-3b9d8',
    authDomain: 'whatsapp12-3b9d8.firebaseapp.com',
    storageBucket: 'whatsapp12-3b9d8.firebasestorage.app',
    measurementId: 'G-R6DTD89HE9',
  );
}
